stages:
- build
- install
- rollback

rollback:
  stage: rollback
  only:
    - galvatron-dev
  script:
    - git checkout galvatron-stable && git pull
    - ./autogen.sh
    - make rpm
    - ls -lh ./noarch/retrace-server-$(cat ./retrace-server-version)*.noarch.rpm
    - sudo dnf localinstall -y ./noarch/retrace-server-$(cat ./retrace-server-version)*.noarch.rpm
    - sudo systemctl restart httpd
  artifacts:
    paths:
    - ./retrace-server-version
    - ./noarch/retrace-server-$(cat ./retrace-server-version)*.noarch.rpm
  tags:
    - retrace-server-development
  when: on_failure

build:
  stage: build
  only:
    - galvatron-dev
  script:
    - ./autogen.sh
    - make rpm
    - ls -lh ./noarch/retrace-server-$(cat ./retrace-server-version)*.noarch.rpm
  artifacts:
    paths:
    - ./retrace-server-version
    - ./noarch/retrace-server-$(cat ./retrace-server-version)*.noarch.rpm
  tags:
    - retrace-server-development

install:
  stage: install
  only:
    - galvatron-dev
  script:
    - sudo dnf localinstall -y ./noarch/retrace-server-$(cat ./retrace-server-version)*.noarch.rpm
    - sudo systemctl restart httpd
  tags:
    - retrace-server-development
