# Workflow
# 0. Create a topic branch based off of 'master' and test
# * PASS: put in PR to 'dev' and go to step #1
# * FAIL: revert to 'last known good'
#
# 1. Merge topic to 'dev' and test
# * PASS: put in PR to 'prod' and go to step #2
# * FAIL: revert to 'last known good'
#
# 2. Merge 'dev' to 'prod' and test
# * PASS: put in PR to 'master' and go to step #3
# * FAIL: revert to 'last known good'
#
# 3. Push to 'master'
#
# Revert
# a) Use 'master' branch for 'last known good' where at all possible.
# * NOTE: There is also a 'galvatron-stable' that can be used but must be kept updated
# b) Use '--force' on 'prod' and 'dev' branches for revert.
# * NOTE: Since 'prod' is protected branch in gitlab, you must first unprotect before --force push
# * See https://gitlab.com/gitlab-org/gitlab-foss/issues/63436
#
# NOTE: For pulls from upstream abrt project, use 'upstream' as topic branch,
# then go to step 0
#
stages:
- build_dev
- install_dev
- build_prod
- install_prod
- rollback

rollback:
  stage: rollback
  only:
    - galvatron-dev
    - galvatron-prod
  script:
    - git checkout galvatron-stable && git pull
    - ./autogen.sh
    - make rpm
    - ls -lh ./noarch/retrace-server-$(cat ./retrace-server-version)*.noarch.rpm
    - sudo dnf localinstall -y ./noarch/retrace-server-$(cat ./retrace-server-version)*.noarch.rpm
    - sudo systemctl restart httpd
  artifacts:
    paths:
    - ./retrace-server-version
    - ./noarch/retrace-server-$(cat ./retrace-server-version)*.noarch.rpm
  tags:
    - retrace-server-development
    - retrace-server-production
  when: on_failure

build_dev:
  stage: build_dev
  only:
    - galvatron-dev
  script:
    - ./autogen.sh sysdeps --install
    - ./autogen.sh
    - make rpm
    - ls -lh ./noarch/retrace-server-$(cat ./retrace-server-version)*.noarch.rpm
  artifacts:
    paths:
    - ./retrace-server-version
    - ./noarch/retrace-server-$(cat ./retrace-server-version)*.noarch.rpm
  tags:
    - retrace-server-development

install_dev:
  stage: install_dev
  only:
    - galvatron-dev
  script:
    - sudo dnf localinstall -y ./noarch/retrace-server-$(cat ./retrace-server-version)*.noarch.rpm
    - sudo systemctl restart httpd
  tags:
    - retrace-server-development

build_prod:
  stage: build_prod
  only:
    - galvatron-prod
  script:
    - ./autogen.sh sysdeps --install
    - ./autogen.sh
    - make rpm
    - ls -lh ./noarch/retrace-server-$(cat ./retrace-server-version)*.noarch.rpm
  artifacts:
    paths:
    - ./retrace-server-version
    - ./noarch/retrace-server-$(cat ./retrace-server-version)*.noarch.rpm
  tags:
    - retrace-server-production

install_prod:
  stage: install_prod
  only:
    - galvatron-prod
  script:
    - sudo dnf localinstall -y ./noarch/retrace-server-$(cat ./retrace-server-version)*.noarch.rpm
    - sudo systemctl restart httpd
  tags:
    - retrace-server-production
